services:
  - type: web
    name: utility-billing
    env: php
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_NAME
        value: Utility Billing
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:lPgxz7Mp1VoufVTObzAYiiAckeHGgijp5SIQyemgvNg=
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /opt/render/project/src/database/database.sqlite
      - key: BROADCAST_DRIVER
        value: log
      - key: CACHE_DRIVER
        value: file
      - key: FILESYSTEM_DISK
        value: local
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: debug
